version: '3'

services:
        natasha:
                build: named-entities
                volumes:
                        - ./named-entities/app:/app
                ports:
                        - 5001:5000

        image-diff:
                build: image-diff
                volumes:
                        - ./image-diff/app:/app
                ports:
                        - 5002:5000
